import { asset } from "./asset.js";
import { scaleCategoryPage } from "./category-scale.js";

const bakeryCardBackground = "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #ffeee4 100%)";

/** Bakery — Figma 299:18 @ 1920px → 1280px (× 2/3). */
const bakeryAt1920 = {
    title: "Bakery",
    copy: "Crafted with rich ingredients and perfected through traditional baking techniques.",
    height: 4710.149,
    hero: { mode: "bakery" },
    heroClassName: "category-hero--bakery-top-nav",
    subnavPlacement: "top",
    newsletter: { top: 3904.649, left: 66, background: "#cfeeef" , className: "category-newsletter--bakery-compact" },
    sections: [
      {
        type: "productCard",
        left: 67.86,
        top: 1253.055,
        width: 824.501,
        height: 824.501,
        background: bakeryCardBackground,
        image: asset('category-bakery-methi-khari.png'),
        imageStyle: { left: 161.37, top: 81.825, width: 587.745, height: 501.045 },
        badge: { label: "BESTSELLER", tone: "muted" },
        title: "Surati\nMethi Khari",
        titleClass: "text-bakery-green product-title-lg",
        titleStyle: { left: 22.5, top: 615, width: 495 },
      },
      {
        type: "productCard",
        left: 988.365,
        top: 1253.055,
        width: 863.781,
        height: 824.501,
        background: bakeryCardBackground,
        image: asset('category-bakery-plain-khari.png'),
        imageStyle: { left: 62.265, top: 255.27, width: 585, height: 498.825 },
        title: "Surati\nPlain Khari",
        titleClass: "text-bakery-brown product-title-lg text-right",
        titleStyle: { right: 43.5, top: 70.5, width: 450 },
      },
      {
        type: "productCard",
        left: 67.86,
        top: 2149.56,
        width: 535.5,
        height: 790.5,
        background: bakeryCardBackground,
        image: asset('category-bakery-jeera-khari.png'),
        imageStyle: { left: 35.4, top: 286.47, width: 461.415, height: 393.45 },
        title: "Surati\nJeera Khari",
        titleClass: "text-bakery-brown product-title-sm",
        titleStyle: { left: 49.5, top: 52.5, width: 427.5 },
      },
      {
        type: "promo",
        left: 665.25,
        top: 2150.115,
        width: 1188,
        height: 799.5,
        background: "#00bea8",
        color: "#00a591",
        buttonColor: "__HEX_4.5__",
        ghost: "Bakery",
        title: "Flaky Layers, Classic\nFlavor",
        copy: "Infused with the aromatic touch of jeera for a rich, savory\nexperience.",
      },
      {
        type: "productCard",
        left: 69,
        top: 3038.85,
        width: 534,
        height: 790.5,
        background: bakeryCardBackground,        image: asset('category-bakery-rusk.png'),
        imageStyle: { left: -60.99, top: 268.44, width: 647.565, height: 522.06 },
        title: "Premium\nRusk",
        titleClass: "text-bakery-gold product-title-lg",
        titleStyle: { left: 49.5, top: 52.5, width: 411 },
      },
      {
        type: "productCard",
        left: 693,
        top: 3038.85,
        width: 534,
        height: 790.5,
        background: bakeryCardBackground,        image: asset('category-bakery-coconut-card.png'),
        imageStyle: { left: 0.75, top: 294.12, width: 533.715, height: 481.965 },
        title: "Coconut\nNankhatai",
        titleClass: "text-bakery-gold product-title-lg",
        titleStyle: { left: 51, top: 52.5, width: 481.5 },
      },
      {
        type: "productCard",
        left: 1317,
        top: 3038.85,
        width: 534,
        height: 790.5,
        background: bakeryCardBackground,        image: asset('category-bakery-surati-nankhatai.png'),
        imageStyle: { left: 0, top: 291.69, width: 536.715, height: 485.895 },
        title: "Surati\nNankhatai",
        titleClass: "text-bakery-gold product-title-lg",
        titleStyle: { left: 51, top: 52.5, width: 481.5 },
      },
    ],
};

export const bakeryPage = scaleCategoryPage(bakeryAt1920);
