import { asset } from "./asset.js";
import { scaleCategoryPage } from "./category-scale.js";

const chikkiCardBackground = "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)";
const chikkiBlueBackground = "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #e3f7ff 100%)";

/** Chikki — Figma 251:18 @ 1920px → 1280px (× 2/3). */
const chikkiAt1920 = {
    title: "Chikki",
    copy: "Crafted with the goodness of jaggery and premium nuts for an authentic treat",
    height: 5630.63,
    hero: { mode: "chikki" },
    heroClassName: "category-hero--chikki-top-nav",
    subnavPlacement: "top",
    newsletter: { top: 4807.13, left: 66, background: "#d8efcf" , className: "category-newsletter--chikki-compact" },
    sections: [
      {
        type: "productCard",
        left: 67.86,
        top: 1253.055,
        width: 824.501,
        height: 824.501,
        background: chikkiCardBackground,
        image: asset('category-chikki-crush-peanut.png'),
        imageStyle: { left: 395.475, top: 80.205, width: 294.525, height: 629.52 },
        badge: { label: "BEST SELLER", tone: "pink" },
        title: "Crush\nPeanut Chikki",
        titleClass: "text-chikki-red product-title-lg",
        titleStyle: { left: 22.5, top: 615, width: 573 },
      },
      {
        type: "productCard",
        left: 988.365,
        top: 1253.055,
        width: 863.781,
        height: 824.501,
        background: chikkiCardBackground,
        image: asset('category-chikki-peanut.png'),
        imageStyle: { left: 106.395, top: 80.205, width: 296.385, height: 633.075 },
        title: "Peanut\nChikki",
        titleClass: "text-indigo product-title-lg text-right",
        titleStyle: { right: 43.5, top: 46.5, width: 399 },
      },
      {
        type: "productCard",
        left: 67.86,
        top: 2149.56,
        width: 535.5,
        height: 790.5,
        background: chikkiCardBackground,
        image: asset('category-chikki-rajgira.png'),
        imageStyle: { left: 172.92, top: 219.27, width: 186.375, height: 670.02 },
        title: "Rajgira Chikki",
        titleClass: "text-chikki-purple product-title-sm",
        titleStyle: { left: 49.5, top: 52.5, width: 436.5 },
      },
      {
        type: "promo",
        left: 665.25,
        top: 2150.115,
        width: 1188,
        height: 799.5,
        background: "#246593",
        color: "#ffffff",
        buttonColor: "#246593",
        ghost: "Chikki",
        title: "Wholesome Crunch,\nNaturally Sweet",
        copy: "Made with nutrient-rich rajgira and pure sweetness for a\nlight, satisfying bite.",
      },
      {
        type: "productCard",
        left: 69,
        top: 3038.85,
        width: 534,
        height: 790.5,
        background: chikkiBlueBackground,        image: asset('category-chikki-dryfruit-mix.png'),
        imageStyle: { left: -47.235, top: 339.12, width: 548.97, height: 345.3 },
        title: "Dry Fruit\nChikki",
        titleClass: "text-chikki-blue product-title-lg",
        titleStyle: { left: 49.5, top: 52.5, width: 390 },
        subtitle: "Mix",
        subtitleStyle: { left: 49.5, top: 193.5, width: 270 },
      },
      {
        type: "productCard",
        left: 693,
        top: 3038.85,
        width: 534,
        height: 790.5,
        background: chikkiBlueBackground,        image: asset('category-chikki-cashew.png'),
        imageStyle: { left: -69.21, top: 336.945, width: 573.795, height: 354.93 },
        title: "Dry Fruit\nChikki",
        titleClass: "text-chikki-blue product-title-lg",
        titleStyle: { left: 49.5, top: 52.5, width: 390 },
        subtitle: "Cashew Nuts",
        subtitleStyle: { left: 49.5, top: 193.5, width: 345 },
      },
      {
        type: "productCard",
        left: 1317,
        top: 3038.85,
        width: 534,
        height: 790.5,
        background: chikkiBlueBackground,        image: asset('category-chikki-almond.png'),
        imageStyle: { left: -69.585, top: 331.77, width: 578.205, height: 364.845 },
        title: "Dry Fruit\nChikki",
        titleClass: "text-chikki-blue product-title-lg",
        titleStyle: { left: 49.5, top: 52.5, width: 390 },
        subtitle: "Almond",
        subtitleStyle: { left: 49.5, top: 193.5, width: 300 },
      },
      {
        type: "promo",
        left: 65.61,
        top: 3917.835,
        width: 1188,
        height: 799.5,
        background: "#246593",
        color: "#ffffff",
        buttonColor: "#246593",
        ghost: "Chikki",
        title: "Light Crunch, Guilt-Free\nSweetness",
        copy: "Made with puffed murmura and natural sweetness for a\nperfectly balanced bite.",
      },
      {
        type: "productCard",
        left: 1315.5,
        top: 3917.835,
        width: 535.5,
        height: 790.5,
        background: chikkiBlueBackground,        image: asset('category-chikki-murmura.png'),
        imageStyle: { left: 101.49, top: 199.605, width: 334.305, height: 694.26 },
        title: "Murmura\nChikki",
        titleClass: "text-chikki-blue product-title-sm text-center",
        titleStyle: { left: 75, top: 52.5, width: 390 },
      },
    ],
};

export const chikkiPage = scaleCategoryPage(chikkiAt1920);
