import "./farali.css";
import { asset } from "./asset.js";
import { scaleCategoryPage } from "./category-scale.js";

/** Farali — Figma 1159:473 @ 1920px → 1280px (× 2/3). */
const faraliAt1920 = {
  title: "Farali",
  copy: "A delightful crunch inspired by tradition, crafted with bold flavors for every fasting moment.",
  /* 2871 + compact newsletter (~329) + 48px breathing room @ 1280 (72 @ 1920) */
  height: 3272,
  hero: { mode: "farali" },
  heroClassName: "category-hero--farali-top-nav",
  subnavPlacement: "top",
  newsletter: {
    top: 2871,
    left: 71,
    background: "#d5cfef",
    className: "category-newsletter--farali-compact",
  },
  sections: [
    {
      type: "productCard",
      left: 68,
      top: 892,
      width: 559,
      height: 385,
      background: "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)",
      image: asset("category-farali-chiwda-tikha.png"),
      imageStyle: { left: 347, top: 60, width: 161, height: 260 },
      title: "Farali\nChiwda Tikha",
      titleClass: "text-farali-brown product-title-farali-lg",
      titleStyle: { left: 50, top: 37, width: 207 },
    },
    {
      type: "productCard",
      left: 679,
      top: 892,
      width: 559,
      height: 385,
      background: "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)",
      image: asset("category-farali-chiwda-mitha.png"),
      imageStyle: { left: 347, top: 57, width: 161, height: 261 },
      title: "Farali Chiwda\nMitha",
      titleClass: "text-indigo product-title-farali-lg",
      titleStyle: { left: 50, top: 47, width: 207 },
      nodeId: "1159:663",
    },
    {
      type: "productCard",
      left: 1289,
      top: 892,
      width: 559,
      height: 385,
      background: "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)",
      image: asset("category-farali-sabudana.png"),
      imageStyle: { left: 336, top: 52, width: 202, height: 278 },
      title: "Farali Sabudana\nChiwada",
      titleClass: "text-indigo product-title-farali-md",
      titleStyle: { left: 37, top: 37, width: 211 },
    },
    {
      type: "promo",
      left: 68,
      top: 1321,
      width: 1338,
      height: 383,
      className: "category-promo--farali-compact",
      background: "#0095be",
      color: "#ffffff",
      buttonColor: "#005676",
      ghost: "Farali",
      title: "Farali Feast, Perfected",
      copy: "Light, crispy chivda crafted for your fasting moments with a perfect touch of sweetness.\nA traditional taste reimagined with premium ingredients and irresistible crunch.",
    },
    {
      type: "productCard",
      left: 1462,
      top: 1321,
      width: 385,
      height: 385,
      background: "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)",
      image: asset("category-farali-kela-chiwda-card.png"),
      imageStyle: { left: 0, top: -12, width: 385, height: 408 },
      title: "Farali Kela\nChiwda",
      titleClass: "text-indigo product-title-farali-md",
      titleStyle: { left: 34, top: 25, width: 143 },
    },
    {
      type: "feature",
      left: 373,
      top: 1762,
      width: 909,
      height: 335,
      className: "category-feature--farali-wide",
      background: "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)",
      kicker: "LIMITED EDITION",
      kickerColor: "#8d2b2f",
      title: "Farali Kela\nChiwda\nTikha",
      titleColor: "#8d2b2f",
      copy: "Packed with bold tikha\nFlavors.",
      buttonColor: "#924db4",
      buttonLabel: "Inquire",
      image: asset("category-farali-kela-chiwda-tikha.png"),
      imageStyle: { left: 469, top: 29, width: 158, height: 255 },
      imageImportantStyle: { height: 255 },
    },
    {
      type: "productCard",
      left: 68,
      top: 2155,
      width: 533,
      height: 641,
      background: "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)",
      image: asset("category-farali-wafers-green-card.png"),
      imageStyle: { left: -2, top: 128, width: 534, height: 579 },
      title: "Farali Kela\nWafers",
      titleClass: "text-deep-green product-title-farali-lg",
      titleStyle: { left: 33, top: 35, width: 245 },
    },
    {
      type: "productCard",
      left: 691,
      top: 2155,
      width: 534,
      height: 641,
      background: "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)",
      image: asset("category-farali-potato-wafers-card.png"),
      imageStyle: { left: 0, top: 138, width: 533, height: 578 },
      title: "Farali Potato\nWafers",
      titleClass: "text-magenta product-title-farali-lg",
      titleStyle: { left: 34, top: 35, width: 321 },
    },
    {
      type: "productCard",
      left: 1315,
      top: 2155,
      width: 533,
      height: 641,
      background: "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)",
      image: asset("category-farali-wafers-white-card.png"),
      imageStyle: { left: -2, top: 128, width: 534, height: 579 },
      title: "Farali Kela\nWafers",
      titleClass: "text-deep-green product-title-farali-lg",
      titleStyle: { left: 33, top: 35, width: 245 },
    },
  ],
};

export const faraliPage = scaleCategoryPage(faraliAt1920);
