import { asset } from "./asset.js";
import { scaleCategoryPage } from "./category-scale.js";

const fryumsCardBackground = "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #faf0ff 100%)";

/** Fryums — Figma 309:23 @ 1920px → 1280px (× 2/3). */
const fryumsAt1920 = {
    title: "Fryums",
    copy: "Playful snacks packed with bold flavors and irresistible crunch.",
    badge: "LOREAM IPSUM",
    height: 5444.18,
    hero: { mode: "fryums" },
    heroClassName: "category-hero--fryums-top-nav",
    subnavPlacement: "top",
    newsletter: { top: 4638.68, left: 66, background: "#cbc6e8" , className: "category-newsletter--fryums-compact" },
    sections: [
      {
        type: "productCard",
        left: 67.86,
        top: 1253.055,
        width: 824.501,
        height: 824.501,
        background: fryumsCardBackground,
        image: asset('category-fryums-tasty-pasta.png'),
        imageStyle: { left: 306.39, top: 83.28, width: 417.96, height: 562.2 },
        badge: { label: "BESTSELLER", tone: "muted" },
        title: "Tasty\nPasta",
        titleClass: "text-fryums-green product-title-lg",
        titleStyle: { left: 22.5, top: 615, width: 493.5 },
      },
      {
        type: "productCard",
        left: 988.365,
        top: 1253.055,
        width: 863.781,
        height: 824.501,
        background: fryumsCardBackground,
        image: asset('category-fryums-magic-abcde.png'),
        imageStyle: { left: 123.225, top: 195.81, width: 420, height: 564.945 },
        title: "Magic\nABCDE",
        titleClass: "text-fryums-red product-title-lg text-right",
        titleStyle: { right: 43.5, top: 70.5, width: 399 },
      },
      {
        type: "productCard",
        left: 67.86,
        top: 2149.56,
        width: 535.5,
        height: 790.5,
        background: fryumsCardBackground,
        image: asset('category-fryums-noodles-sticks.png'),
        imageStyle: { left: 96.915, top: 262.545, width: 345.57, height: 430.29 },
        title: "Farali Kela\nChiwda Mitha",
        titleClass: "text-fryums-purple product-title-sm",
        titleStyle: { left: 49.5, top: 52.5, width: 499.5 },
      },
      {
        type: "promo",
        left: 665.25,
        top: 2150.115,
        width: 1188,
        height: 799.5,
        background: "#0095be",
        color: "#005676",
        buttonColor: "__HEX_4.5__",
        ghost: "Fryums",
        title: "Light Crunch, Sweet\nDelight",
        copy: "A perfect mix of crispy textures and filled with flavours to\ndeepen your taste buds.",
      },
      {
        type: "productCard",
        left: 70.5,
        top: 3021.615,
        width: 707.518,
        height: 707.518,
        background: fryumsCardBackground,
        image: asset('category-fryums-ringoli-tomato-rings.png'),
        imageStyle: { left: 56.82, top: 101.25, width: 605.88, height: 605.88 },
        title: "Ringoli\nTomato Rings",
        titleClass: "text-fryums-ring product-title-sm text-center",
        titleStyle: { left: 117, top: 49.5, width: 474 },
      },
      {
        type: "feature",
        left: 838.5,
        top: 3021.615,
        width: 1011,
        height: 708,
        background: fryumsCardBackground,
        kicker: "LIMITED EDITION",
        kickerColor: "#d83913",
        title: "Salted\nFinger Pipe",
        titleColor: "__HEX_7.5__",
        copy: "Perfectly salted bites with a\ncrisp texture that keeps you\nmunching.",
        buttonColor: "undefined",
        image: asset('category-fryums-salted-finger-pipe.png'),
        imageStyle: { left: 456, top: 48, width: 534, height: 589.5 },
      },
      {
        type: "productCard",
        left: 69,
        top: 3789,
        width: 534,
        height: 790.5,
        background: fryumsCardBackground,
        image: asset('category-fryums-wheels-chaska.png'),
        imageStyle: { left: 93.615, top: 268.605, width: 345, height: 429.585 },
        title: "Wheels\nChaska",
        titleClass: "text-fryums-darkgreen product-title-lg",
        titleStyle: { left: 49.5, top: 52.5, width: 367.5 },
      },
      {
        type: "productCard",
        left: 693,
        top: 3789,
        width: 534,
        height: 790.5,
        background: fryumsCardBackground,
        image: asset('category-fryums-crunchy-cups.png'),
        imageStyle: { left: 119.82, top: 251.37, width: 345, height: 464.07 },
        title: "Crunchy\nCups",
        titleClass: "text-fryums-magenta product-title-lg",
        titleStyle: { left: 51, top: 52.5, width: 481.5 },
      },
      {
        type: "productCard",
        left: 1317,
        top: 3789,
        width: 534,
        height: 790.5,
        background: fryumsCardBackground,
        image: asset('category-fryums-cone-cap.png'),
        imageStyle: { left: 97.365, top: 251.37, width: 345, height: 464.055 },
        title: "Cone\nCap",
        titleClass: "text-fryums-deepgreen product-title-lg",
        titleStyle: { left: 51, top: 52.5, width: 481.5 },
      },
    ],
};

export const fryumsPage = scaleCategoryPage(fryumsAt1920);
