import { asset } from "./asset.js";
import { scaleCategoryPage } from "./category-scale.js";

const khakhraCardBackground = "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #ffeee4 100%)";

/** Khakhra — Figma 257:18 @ 1920px → 1280px (× 2/3). */
const khakhraAt1920 = {
    title: "Khakhra",
    copy: "Thin, roasted to perfection with authentic Indian flavors in every bite.",
    height: 5613.269,
    hero: { mode: "khakhra" },
    heroClassName: "category-hero--khakhra-top-nav",
    subnavPlacement: "top",
    newsletter: { top: 4807.769, left: 66, background: "#efd6cf" , className: "category-newsletter--khakhra-compact" },
    sections: [
      {
        type: "productCard",
        left: 67.86,
        top: 1253.055,
        width: 824.501,
        height: 824.501,
        background: khakhraCardBackground,
        image: asset('category-khakhra-masala.png'),
        imageStyle: { left: 223.23, top: 82.44, width: 494.76, height: 540.225 },
        badge: { label: "BESTSELLER", tone: "muted" },
        title: "Masala\nKhakhra",
        titleClass: "text-khakhra-blue product-title-lg",
        titleStyle: { left: 22.5, top: 615, width: 493.5 },
      },
      {
        type: "productCard",
        left: 988.365,
        top: 1253.055,
        width: 863.781,
        height: 824.501,
        background: khakhraCardBackground,
        image: asset('category-khakhra-10.5grain.png'),
        imageStyle: { left: 123.75, top: 256.83, width: 480.195, height: 528.18 },
        title: "10.5 Grain\nKhakhra",
        titleClass: "text-khakhra-brown product-title-lg text-right",
        titleStyle: { right: 43.5, top: 70.5, width: 399 },
      },
      {
        type: "productCard",
        left: 67.86,
        top: 2149.56,
        width: 535.5,
        height: 790.5,
        background: khakhraCardBackground,
        image: asset('category-khakhra-fafda.png'),
        imageStyle: { left: 90.75, top: 267.27, width: 365.985, height: 387.06 },
        title: "Fafda Khakhra",
        titleClass: "text-khakhra-red product-title-sm",
        titleStyle: { left: 49.5, top: 52.5, width: 450 },
      },
      {
        type: "promo",
        left: 665.25,
        top: 2150.115,
        width: 1188,
        height: 799.5,
        background: "#be004b",
        color: "#be004b",
        buttonColor: "__HEX_4.5__",
        ghost: "Khakhra",
        title: "Bold Crunch, Gujarati\nStyle",
        copy: "Infused with the iconic taste of khakhra, crafted into a\nperfectly packed stuff.",
      },
      {
        type: "productCard",
        left: 69,
        top: 3038.85,
        width: 534,
        height: 790.5,
        background: khakhraCardBackground,
        image: asset('category-khakhra-jeera.png'),
        imageStyle: { left: 67.35, top: 271.35, width: 375.135, height: 414.585 },
        title: "Jeera\nKhakhra",
        titleClass: "text-khakhra-red product-title-lg",
        titleStyle: { left: 49.5, top: 52.5, width: 411 },
      },
      {
        type: "productCard",
        left: 693,
        top: 3038.85,
        width: 534,
        height: 790.5,
        background: khakhraCardBackground,
        image: asset('category-khakhra-panipuri.png'),
        imageStyle: { left: 80.7, top: 271.35, width: 372.615, height: 414.585 },
        title: "Pani Puri\nKhakhra",
        titleClass: "text-khakhra-red product-title-lg",
        titleStyle: { left: 51, top: 52.5, width: 481.5 },
      },
      {
        type: "productCard",
        left: 1317,
        top: 3038.85,
        width: 534,
        height: 790.5,
        background: khakhraCardBackground,
        image: asset('category-khakhra-oats.png'),
        imageStyle: { left: 78, top: 271.35, width: 375, height: 414.585 },
        title: "Oats\nKhakhra",
        titleClass: "text-khakhra-red product-title-lg",
        titleStyle: { left: 51, top: 52.5, width: 481.5 },
      },
      {
        type: "productCard",
        left: 69,
        top: 3910.35,
        width: 534,
        height: 790.5,
        background: khakhraCardBackground,
        image: asset('category-khakhra-chorafali.png'),
        imageStyle: { left: 74.85, top: 273.465, width: 375.135, height: 416.16 },
        title: "Chorafali\nKhakhra",
        titleClass: "text-khakhra-red product-title-lg",
        titleStyle: { left: 49.5, top: 52.5, width: 411 },
      },
      {
        type: "productCard",
        left: 693,
        top: 3910.35,
        width: 534,
        height: 790.5,
        background: khakhraCardBackground,
        image: asset('category-khakhra-bajri.png'),
        imageStyle: { left: 79.5, top: 273.72, width: 375, height: 415.92 },
        title: "Bajri\nKhakhra",
        titleClass: "text-khakhra-red product-title-lg",
        titleStyle: { left: 51, top: 52.5, width: 481.5 },
      },
      {
        type: "productCard",
        left: 1317,
        top: 3910.35,
        width: 534,
        height: 790.5,
        background: khakhraCardBackground,
        image: asset('category-khakhra-garlic.png'),
        imageStyle: { left: 85.095, top: 279.405, width: 363.825, height: 404.88 },
        title: "Garlic\nKhakhra",
        titleClass: "text-khakhra-red product-title-lg",
        titleStyle: { left: 51, top: 52.5, width: 481.5 },
      },
    ],
};

export const khakhraPage = scaleCategoryPage(khakhraAt1920);
