import "./namkeen.css";
import { asset } from "./asset.js";
import { scaleCategoryPage } from "./category-scale.js";

const namkeenCardBackground = "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #e3f7ff 100%)";

/** Namkeen — Figma 173:10 @ 1920px → 1280px (× 2/3). */
const namkeenAt1920 = {
    title: "Namkeen",
    copy: "A rich blend of spices and textures crafted to satisfy every savory craving.",
    height: 5972,
    /* Pull grid up under compact hero (~40px below packs vs ~140px). @1920 → ×2/3 in layout. */
    compactContentShift: 156,
    hero: { mode: "namkeen" },
    heroClassName: "category-hero--namkeen-top-nav",
    subnavPlacement: "top",
    newsletter: { top: 5596, left: 66, background: "#efcfcf", className: "category-newsletter--namkeen-compact" },
    sections: [
      {
        type: "productCard",
        left: 70,
        top: 1259.25,
        width: 536,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-shahi-mixture.png"),
        imageStyle: { left: 141.5, top: 74.25, width: 253, height: 410 },
        title: "Mixture",
        titleClass: "text-namkeen-plum product-title-namkeen-sm",
        titleStyle: { left: 194, top: 23.25, width: 148 },
        nodeId: "1206:390",
      },
      {
        type: "promo",
        className: "category-promo--namkeen-compact",
        left: 658,
        top: 1254,
        width: 1188,
        height: 388,
        background: "#d1b4d7",
        color: "#ffffff",
        buttonColor: "#b05abe",
        ghost: "Namkeen",
        title: "The Secret Behind Every\nPerfect Bite",
        copy: "Carefully selected ingredients and expert craftsmanship\ncome together for unmatched crunch.",
        nodeId: "1206:372",
      },
      {
        type: "productCard",
        left: 70,
        top: 1718,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-madras-mix.png"),
        imageStyle: { left: 295, top: 80, width: 170, height: 276.272 },
        title: "Madras\nMix",
        titleClass: "text-namkeen-gray product-title-namkeen-sm",
        titleStyle: { left: 33, top: 14, width: 321 },
        nodeId: "1206:444",
      },
      {
        type: "productCard",
        left: 682,
        top: 1718,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-lemon-mint-bhel.png"),
        imageStyle: { left: 310, top: 80, width: 170, height: 274.791 },
        title: "Lemon Mint\nBhel",
        titleClass: "text-namkeen-gray product-title-namkeen-sm",
        titleStyle: { left: 34.25, top: 34.78, width: 321 },
        nodeId: "1206:435",
      },
      {
        type: "productCard",
        left: 1294,
        top: 1718,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-kenyan-chiwda-hot.png"),
        imageStyle: { left: 310, top: 80, width: 170, height: 275 },
        title: "Kenyan\nChiwda Hot",
        titleClass: "text-namkeen-gray product-title-namkeen-sm",
        titleStyle: { left: 35.5, top: 34.78, width: 321 },
        nodeId: "1206:427",
      },
      {
        type: "productCard",
        left: 68,
        top: 2155,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-shakkarpara.png"),
        imageStyle: { left: 192, top: 95, width: 170, height: 275 },
        title: "Shakkarpara",
        titleClass: "text-namkeen-plum product-title-namkeen-sm text-center",
        titleStyle: { left: 158, top: 14, width: 240 },
        nodeId: "1206:467",
      },
      {
        type: "productCard",
        left: 679,
        top: 2155,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-chana-jor-masala.png"),
        imageStyle: { left: 192, top: 95, width: 170, height: 274 },
        title: "Chana Jor Masala",
        titleClass: "text-namkeen-blue product-title-namkeen-sm text-center",
        titleStyle: { left: 117, top: 14, width: 321 },
        nodeId: "1206:473",
      },
      {
        type: "productCard",
        left: 1290,
        top: 2155,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-mini-samosa.png"),
        imageStyle: { left: 192, top: 97, width: 170, height: 275 },
        title: "Mini Samosa",
        titleClass: "text-namkeen-plum product-title-namkeen-sm text-center",
        titleStyle: { left: 161, top: 14, width: 234 },
        nodeId: "1206:477",
      },
      {
        type: "productCard",
        left: 679,
        top: 2592,
        width: 555,
        height: 385,
        background: "radial-gradient(circle, #f6f6f6 0%, #e3f7ff 100%)",
        image: asset("category-namkeen-tikhi-sev.png"),
        imageStyle: { left: 161, top: 88, width: 219.486, height: 283 },
        title: "Tikhi Sev",
        titleClass: "text-namkeen-blue product-title-namkeen-lg",
        titleStyle: { left: 163.5, top: 23.5, width: 195 },
        nodeId: "1206:514",
      },
      {
        type: "productCard",
        left: 68,
        top: 2592,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-dry-kachori.png"),
        imageStyle: { left: 195, top: 21, width: 170, height: 279 },
        title: "Dry Kachori",
        titleClass: "text-namkeen-blue product-title-namkeen-sm",
        titleStyle: { left: 170, top: 305, width: 214 },
        nodeId: "1206:485",
      },
      {
        type: "productCard",
        left: 1290,
        top: 2592,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-royal-moong.png"),
        imageStyle: { left: 126, top: 24, width: 280, height: 275 },
        title: "Bhadran Moong",
        titleClass: "text-namkeen-blue product-title-namkeen-sm",
        titleStyle: { left: 129, top: 305, width: 296 },
        nodeId: "1206:497",
      },
      {
        type: "productCard",
        left: 69,
        top: 3029,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-tomato-soya-sticks.png"),
        imageStyle: { left: 317, top: 74, width: 180.389, height: 291.238 },
        title: "Tomato\nSoya Sticks",
        titleClass: "text-namkeen-gray product-title-namkeen-sm",
        titleStyle: { left: 36, top: 33, width: 301 },
        nodeId: "1210:547",
      },
      {
        type: "productCard",
        left: 678,
        top: 3029,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-masala-soya-sticks.png"),
        imageStyle: { left: 316, top: 76, width: 180.39, height: 291.793 },
        title: "Masala Soya\nSticks",
        titleClass: "text-namkeen-gray product-title-namkeen-sm",
        titleStyle: { left: 46, top: 35, width: 321 },
        nodeId: "1210:537",
      },
      {
        type: "productCard",
        left: 1291,
        top: 3029,
        width: 555,
        height: 385,
        background: namkeenCardBackground,
        image: asset("category-namkeen-spicy-potato-sticks.png"),
        imageStyle: { left: 343, top: 76, width: 180.39, height: 291.585 },
        title: "Spicy Potato\nSticks",
        titleClass: "text-namkeen-gray product-title-namkeen-sm",
        titleStyle: { left: 40, top: 35, width: 321 },
        nodeId: "1210:526",
      },
      {
        type: "promo",
        className: "category-promo--namkeen-compact",
        left: 66,
        top: 3466,
        width: 1780,
        height: 429,
        background: "#d90000",
        color: "#ffffff",
        copyColor: "#ffffff",
        buttonColor: "#d90000",
        ghost: "Namkeen",
        title: "Crispy Perfection,\nEvery Time",
        copy: "Made with fine ingredients and perfectly spiced for that\nclassic crunchy experience.",
        nodeId: "1210:566",
      },
      {
        type: "productCard",
        left: 70,
        top: 3947,
        width: 860,
        height: 550,
        background: namkeenCardBackground,
        image: asset("category-namkeen-jeera-puri.png"),
        imageStyle: { left: 290, top: 118, width: 250, height: 395.247 },
        title: "Jeera Puri",
        titleClass: "text-namkeen-red product-title-namkeen-lg text-center",
        titleStyle: { left: 187, top: 46, width: 450 },
        nodeId: "1210:576",
      },
      {
        type: "productCard",
        left: 952,
        top: 3947,
        width: 860,
        height: 550,
        background: "radial-gradient(circle, #f6f6f6 0%, #e3f7ff 100%)",
        image: asset("category-namkeen-methi-puri.png"),
        imageStyle: { left: 305, top: 166, width: 250, height: 306.605 },
        title: "Methi Puri",
        titleClass: "text-namkeen-blue product-title-namkeen-lg text-right",
        titleStyle: { top: 49, width: 480, left: "auto" },
        titleImportantStyle: { right: 188.333 },
        nodeId: "1210:584",
      },
      {
        type: "productCard",
        left: 70,
        top: 4550,
        width: 860,
        height: 550,
        background: namkeenCardBackground,
        image: asset("category-namkeen-plain-nylon-papdi.png"),
        imageStyle: { left: 290, top: 25, width: 250, height: 395 },
        title: "Plain Nylon Papdi",
        titleClass: "text-namkeen-plum product-title-namkeen-lg text-center",
        titleStyle: { left: 74, top: 430, width: 676 },
        nodeId: "1210:590",
      },
      {
        type: "productCard",
        left: 952,
        top: 4550,
        width: 860,
        height: 550,
        background: namkeenCardBackground,
        image: asset("category-namkeen-papad-chavana.png"),
        imageStyle: { left: 305, top: 22, width: 250, height: 404.591 },
        title: "Papad Chavana",
        titleClass: "text-namkeen-blue product-title-namkeen-lg text-right",
        titleStyle: { top: 430, width: 632, left: "auto" },
        titleImportantStyle: { right: 117.667 },
        nodeId: "1210:598",
      },
      {
        type: "spotlight",
        hideOnMobile: true,
        top: 5144,
        title: "Royal\nCrunch...",
        nodeId: "1215:605",
        items: [
          { image: asset('category-namkeen-royal-peanuts.png') },
          { image: asset('category-namkeen-chana-jor-masala.png') },
        ],
      },
    ],
};

export const namkeenPage = scaleCategoryPage(namkeenAt1920);
