import { asset } from "./asset.js";
import { scaleCategoryPage } from "./category-scale.js";

const namkeenCardBackground = "radial-gradient(circle at 50% 50%, #f6f6f6 0%, #e3f7ff 100%)";

/** Namkeen — Figma 173:10 @ 1920px → 1280px (× 2/3). */
const namkeenAt1920 = {
    title: "Namkeen",
    copy: "A rich blend of spices and textures crafted to satisfy every savory craving.",
    badge: "LOREAM IPSUM",
    height: 9789.252,
    hero: { mode: "namkeen" },
    heroClassName: "category-hero--namkeen-top-nav",
    subnavPlacement: "top",
    newsletter: { top: 8983.752, left: 66, background: "#efcfcf", className: "category-newsletter--namkeen-compact" },
    sections: [
      {
        type: "productCard",
        left: 69.023,
        top: 1259.25,
        width: 535.5,
        height: 790.5,
        background: namkeenCardBackground,
        image: asset('category-namkeen-shahi-mixture.png'),
        imageStyle: { left: 103.2, top: 199.5, width: 329.229, height: 532.5 },
        title: "Mixture",
        titleClass: "text-namkeen-plum product-title-namkeen-sm",
        titleStyle: { left: 156, top: 66, width: 223.5 },
      },
      {
        type: "promo", className: "category-promo--namkeen-compact",
        left: 657,
        top: 1254,
        width: 1188,
        height: 799.5,
        background: "#cda0d3",
        color: "#ffffff",
        buttonColor: "#b05abe",
        ghost: "Namkeen",
        title: "The Secret Behind Every\nPerfect Bite",
        copy: "Carefully selected ingredients and expert craftsmanship\ncome together for unmatched crunch.",
      },
      {
        type: "productCard",
        left: 69,
        top: 2125.5,
        width: 534,
        height: 790.5,
        background: namkeenCardBackground,
        image: asset('category-namkeen-madras-mix.png'),
        imageStyle: { left: 129.45, top: 290.7, width: 255, height: 414.408 },
        title: "Madras\nMix",
        titleClass: "text-namkeen-blue product-title-namkeen-sm",
        titleStyle: { left: 49.5, top: 52.5, width: 411 },
      },
      {
        type: "productCard",
        left: 693,
        top: 2125.5,
        width: 534,
        height: 790.5,
        background: namkeenCardBackground,
        image: asset('category-namkeen-lemon-mint-bhel.png'),
        imageStyle: { left: 139.5, top: 281.55, width: 255, height: 412.187 },
        title: "Lemon Mint\nBhel",
        titleClass: "text-namkeen-blue product-title-namkeen-sm",
        titleStyle: { left: 51.375, top: 52.5, width: 481.5 },
      },
      {
        type: "productCard",
        left: 1317,
        top: 2125.5,
        width: 534,
        height: 790.5,
        background: namkeenCardBackground,
        image: asset('category-namkeen-kenyan-chiwda-hot.png'),
        imageStyle: { left: 142.5, top: 281.55, width: 255, height: 412.187 },
        title: "Kenyan\nChiwda Hot",
        titleClass: "text-namkeen-blue product-title-namkeen-sm",
        titleStyle: { left: 53.25, top: 52.5, width: 480 },
      },
      {
        type: "arrow",
        left: 34.86,
        top: 2503.5,
        direction: "left",
      },
      {
        type: "arrow",
        left: 1885.5,
        top: 2503.5,
        direction: "right",
      },
      {
        type: "productCard",
        left: 67.86,
        top: 2988,
        width: 824.501,
        height: 824.501,
        background: namkeenCardBackground,
        image: asset('category-namkeen-shakkarpara.png'),
        imageStyle: { left: 221.7, top: 177.9, width: 375, height: 606.048 },
        title: "Shakkarpara",
        titleClass: "text-namkeen-red product-title-namkeen-lg text-center",
        titleStyle: { left: 191.7, top: 46.65, width: 441 },
      },
      {
        type: "productCard",
        left: 988.365,
        top: 2988,
        width: 863.781,
        height: 824.501,
        background: namkeenCardBackground,
        image: asset('category-namkeen-chana-jor-masala.png'),
        imageStyle: { left: 244.35, top: 169.8, width: 375, height: 605.613 },
        title: "Chana Jor Masala",
        titleClass: "text-namkeen-blue product-title-namkeen-lg text-center",
        titleStyle: { left: 72, top: 49.5, width: 720 },
      },
      {
        type: "productCard",
        left: 67.86,
        top: 3884.501,
        width: 824.501,
        height: 824.501,
        background: namkeenCardBackground,
        image: asset('category-namkeen-mini-samosa.png'),
        imageStyle: { left: 224.7, top: 61.05, width: 375, height: 606.396 },
        title: "Mini Samosa",
        titleClass: "text-namkeen-plum product-title-namkeen-lg text-center",
        titleStyle: { left: 123.45, top: 706.65, width: 577.5 },
      },
      {
        type: "productCard",
        left: 988.365,
        top: 3884.501,
        width: 863.781,
        height: 824.501,
        background: namkeenCardBackground,
        image: asset('category-namkeen-dry-kachori.png'),
        imageStyle: { left: 244.35, top: 57, width: 375, height: 614.514 },
        title: "Dry Kachori",
        titleClass: "text-namkeen-blue product-title-namkeen-lg text-right",
        titleStyle: { right: 138.6, top: 706.65, width: 540 },
      },
      {
        type: "promo", className: "category-promo--namkeen-compact",
        left: 69.023,
        top: 4784.751,
        width: 1188,
        height: 799.5,
        background: "#d90000",
        color: "#ffffff",
        copyColor: "#ffffff",
        buttonColor: "#d90000",
        ghost: "Namkeen",
        title: "Crispy Perfection,\nEvery Time",
        copy: "Made with fine ingredients and perfectly spiced for that\nclassic crunchy experience.",
      },
      {
        type: "productCard",
        left: 1309.5,
        top: 4789.251,
        width: 535.5,
        height: 790.5,
        background: namkeenCardBackground,
        image: asset('category-namkeen-tikhi-sev.png'),
        imageStyle: { left: 103.2, top: 199.5, width: 329.229, height: 532.5 },
        title: "Sev / Gathiya",
        titleClass: "text-namkeen-plum product-title-namkeen-sm text-center",
        titleStyle: { left: 88.5, top: 66, width: 358.5 },
      },
      {
        type: "productCard",
        left: 69,
        top: 5656.251,
        width: 534,
        height: 790.5,
        background: namkeenCardBackground,
        image: asset('category-namkeen-tomato-soya-sticks.png'),
        imageStyle: { left: 139.5, top: 290.1, width: 255, height: 411.699 },
        title: "Tomato\nSoya Sticks",
        titleClass: "text-namkeen-blue product-title-namkeen-sm",
        titleStyle: { left: 49.5, top: 52.5, width: 411 },
      },
      {
        type: "productCard",
        left: 693,
        top: 5656.251,
        width: 534,
        height: 790.5,
        background: namkeenCardBackground,
        image: asset('category-namkeen-masala-soya-sticks.png'),
        imageStyle: { left: 139.5, top: 287.55, width: 255, height: 412.481 },
        title: "Masala Soya\nSticks",
        titleClass: "text-namkeen-blue product-title-namkeen-sm",
        titleStyle: { left: 51.375, top: 52.5, width: 481.5 },
      },
      {
        type: "productCard",
        left: 1317,
        top: 5656.251,
        width: 534,
        height: 790.5,
        background: namkeenCardBackground,
        image: asset('category-namkeen-spicy-potato-sticks.png'),
        imageStyle: { left: 142.5, top: 287.85, width: 255, height: 412.187 },
        title: "Spicy Potato\nSticks",
        titleClass: "text-namkeen-blue product-title-namkeen-sm",
        titleStyle: { left: 53.25, top: 52.5, width: 480 },
      },
      {
        type: "arrow",
        left: 39.3,
        top: 6018,
        direction: "left",
      },
      {
        type: "arrow",
        left: 1845,
        top: 6018,
        direction: "right",
      },
      {
        type: "productCard",
        left: 67.86,
        top: 6518.751,
        width: 824.501,
        height: 824.501,
        background: namkeenCardBackground,
        image: asset('category-namkeen-jeera-puri.png'),
        imageStyle: { left: 225.3, top: 176.4, width: 375, height: 592.871 },
        title: "Jeera Puri",
        titleClass: "text-namkeen-red product-title-namkeen-lg text-center",
        titleStyle: { left: 187.2, top: 46.65, width: 450 },
      },
      {
        type: "productCard",
        left: 988.365,
        top: 6518.751,
        width: 863.781,
        height: 824.501,
        background: namkeenCardBackground,
        image: asset('category-namkeen-methi-puri.png'),
        imageStyle: { left: 244.35, top: 172.35, width: 375, height: 606.156 },
        title: "Methi Puri",
        titleClass: "text-namkeen-blue product-title-namkeen-lg text-right",
        titleStyle: { right: 182.1, top: 49.5, width: 480 },
      },
      {
        type: "productCard",
        left: 67.86,
        top: 7415.252,
        width: 824.501,
        height: 824.501,
        background: namkeenCardBackground,
        image: asset('category-namkeen-plain-nylon-papdi.png'),
        imageStyle: { left: 224.7, top: 73.2, width: 375, height: 606.156 },
        title: "Plain Nylon Papdi",
        titleClass: "text-namkeen-plum product-title-namkeen-lg text-center",
        titleStyle: { left: 73.95, top: 706.65, width: 676.5 },
      },
      {
        type: "productCard",
        left: 988.365,
        top: 7415.252,
        width: 863.781,
        height: 824.501,
        background: namkeenCardBackground,
        image: asset('category-namkeen-papad-chavana.png'),
        imageStyle: { left: 244.35, top: 66, width: 375, height: 606.887 },
        title: "Papad Chavana",
        titleClass: "text-namkeen-blue product-title-namkeen-lg text-right",
        titleStyle: { right: 123.6, top: 706.65, width: 631.5 },
      },
      {
        type: "spotlight",
        top: 8311.752,
        title: "Royal\nCrunch...",
        nodeId: "1206:93",
        items: [
          { image: asset('category-namkeen-royal-moong.png') },
          { image: asset('category-namkeen-royal-peanuts.png') },
          { image: asset('category-namkeen-chana-jor-masala.png') },
        ],
      },
    ],
};

export const namkeenPage = scaleCategoryPage(namkeenAt1920);
